### ISSUE TITLE
Novidade?

### ISSUE THREAD

**Issue by leandrossantos** [ACBrNet/ACBr.Net.CTe#1]
Alguma novidade nesse projeto, tenho interesse e necessidade de usá-lo aqui onde trabalho.

**Comment by rftd** [comment]
No momento estou concentrando os meus esforços no NFSe.

**Comment by leandrossantos** [comment]
Opa @rftd nessa ai também tenho interesse. Já tem a tela de exemplo pronta com os campos de como fazer a configuração?

**Comment by rftd** [comment]
Ainda estamos terminando de implementar o ginfes e o DSF ai vou terminar o demo para liberar uma versão beta.

**Comment by leandrossantos** [comment]
Certo, estou precisando dos provedores: Pronim, PronimV2, WebISS, ISSNET, FISSLEX e Fiorilli.
Porque a DLL que uso hoje só consigo usar a FISSLEX em apenas uma cidade, para novas cidades mesmo que seja o mesmo provedor eles não comercializam a licença. Ai acabo ficando amarrado em apenas uma cidade na parte de NFSe.

**Comment by rftd** [comment]
Conforme vou tendo tempo os provedores vão sendo implementados. o Ginfes o Rodolfo ta me auxiliando com os teste e seguindo a implementação que eu já tinha do DSF.
Assim que eu tiver alguns provedores implementados pretendo voltar a CTe que eu já tinha iniciado algumas coisas.

**Comment by leandrossantos** [comment]
Beleza, para os provedores Pronim e FISSLEX eu consigo fazer os testes por aqui viu.
