### ISSUE TITLE
CCE - retEventoCTe  com Id "em branco"

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.CTe#15]
O CCe é transmitido em vinculado ao CTe, entretanto o ID do retEventoCTe não é preenchido.

![image](https://user-images.githubusercontent.com/15945003/44003350-b8c268da-9e27-11e8-97c0-4a3479300e4e.png)

O ID está correto no eventoCTe

![image](https://user-images.githubusercontent.com/15945003/44003367-e4696f56-9e27-11e8-8612-19d00bb61f80.png)

**Comment by marcosgerene** [comment]
@rftd 
Na verdade pelo que vi esse ID nem deveria existir ai, notei também um cUF 00

**Comment by rftd** [comment]
O campo existe no Schema mas aparentemente a SEFAZ não retorna.
Coloquei o atributo como opcional para não serializar caso a Sefaz não informe.
