### ISSUE TITLE
Novo commit

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.CTe#2]
Boa tarde @rftd ,

Termino essa semana de desenhar as telas do meu sistema e de montar meu banco de dados para o CTE, eu até estava cogitando usar o ACBrMonitor Plus ou algo do tipo, mas vi seu commit agora e fiquei bem animado....

Gostaria de te parabenizar pela iniciativa e dizer que assim como fizemos com o Sat, assim que tiver liberado o CTe já vou iniciar meus testes e tentar ajudar no que for possível dentro das minhas limitações...

Abraço e meus parabéns pelo projeto!

**Comment by leandrossantos** [comment]
@rftd valeu pelo commit, passei o fds mexendo com CTe aqui, vou pegar suas classes e comparar com as minhas para ver se esqueci algo.

Valeu e parabéns.

PS: Agora Aguardando as classes do MDFe também, rs.
