### ISSUE TITLE
Liberação do Projeto

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.CTe#3]
Bom dia @rftd ,

Sobre o CTe, esta agora é minha prioridade de desenvolvimento, gostaria de saber em que posso ajudar, o que está pendente, entre outros para gente poder liberar o projeto na versão beta.

Abraço

**Comment by rftd** [comment]
No momento a classe CTe esta apenas funcionando para a CTe 3.0 tem que fazer os ajustes para CTe 2.0.
e testar a leitura e geração das XML

**Comment by marcosgerene** [comment]
Ja esta funcionando então? vou fazer os testes,  se achar bug posto aqui 

abraço

**Comment by rftd** [comment]
Sim esta funcionando apenas a geração/leitura do XML da CTe 3.0, a parte de envio eu estou fazendo ainda.

**Comment by marcosgerene** [comment]
## Não consegui compilar, problema com os ENUMs

**Update 1:**

![erro](https://cloud.githubusercontent.com/assets/15945003/20259252/0515794e-aa3b-11e6-9e0b-86b89586c92d.png)

**Comment by rftd** [comment]
Pelo erro você esta com dll desatualizada não esta usando a ultima versão beta disponivel no nuget da lib DFe.Core

**Comment by marcosgerene** [comment]
![nuget](https://cloud.githubusercontent.com/assets/15945003/20305514/0543a7c8-ab1d-11e6-8636-03f85386204a.png)

**Comment by rftd** [comment]
Esta lib é de pre-release ainda então você precisa marcar o campo Include prerelease.
Obs.: os serviços ainda precisam de ajustes para funcionar 100% devido ao .net framework usar por padrão o tipo Soap 1.2 com Andressing e os webservice do CTe usam Soap 1.2 sem Andressing.
Este problema já foi sanado testando agora a geração do envelope.

**Comment by rftd** [comment]
<cteStatusServicoCTResult xmlns="http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico">
      <retConsStatServCte xmlns="http://www.portalfiscal.inf.br/cte" versao="2.00">
        <tpAmb>2</tpAmb>
        <verAplic>RS20160930175504</verAplic>
        <cStat>107</cStat>
        <xMotivo>Servico em Operacao</xMotivo>
        <cUF>33</cUF>
        <dhRecbto>2016-11-15T11:46:16</dhRecbto>
        <tMed>1</tMed>
      </retConsStatServCte>
    </cteStatusServicoCTResult>

**Comment by rftd** [comment]
Resolvido os problemas dos clientes.

**Comment by marcosgerene** [comment]
Consegui compilar, comecei hoje a implementar, acho que ainda essa semana consigo começar os testes.
